/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Time = bigint;
export interface Token {
  'fdv' : number,
  'change24h' : number,
  'marketCap' : number,
  'name' : string,
  'liquidity' : number,
  'volume24h' : number,
  'holders' : bigint,
  'price' : number,
  'symbol' : string,
}
export interface Trade {
  'tradeType' : { 'buy' : null } |
    { 'sell' : null },
  'timestamp' : Time,
  'tokenPair' : string,
  'price' : number,
  'amount' : number,
  'symbol' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addOrUpdateToken' : ActorMethod<[Token], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buyToken' : ActorMethod<[string, number], undefined>,
  'getAllTokens' : ActorMethod<[], Array<Token>>,
  'getAllTrades' : ActorMethod<[], Array<Trade>>,
  'getCallerHoldings' : ActorMethod<
    [],
    Array<[{ 'amount' : number, 'symbol' : string }, Token]>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHoldings' : ActorMethod<
    [Principal],
    Array<[{ 'amount' : number, 'symbol' : string }, Token]>
  >,
  'getToken' : ActorMethod<[string], [] | [Token]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSampleData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sellToken' : ActorMethod<[string, number], undefined>,
  'updateTokenPrice' : ActorMethod<[string, number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];