/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Token = IDL.Record({
  'fdv' : IDL.Float64,
  'change24h' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'liquidity' : IDL.Float64,
  'volume24h' : IDL.Float64,
  'holders' : IDL.Nat,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Trade = IDL.Record({
  'tradeType' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
  'timestamp' : Time,
  'tokenPair' : IDL.Text,
  'price' : IDL.Float64,
  'amount' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOrUpdateToken' : IDL.Func([Token], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buyToken' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'getAllTokens' : IDL.Func([], [IDL.Vec(Token)], ['query']),
  'getAllTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getCallerHoldings' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Record({ 'amount' : IDL.Float64, 'symbol' : IDL.Text }),
            Token,
          )
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHoldings' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Record({ 'amount' : IDL.Float64, 'symbol' : IDL.Text }),
            Token,
          )
        ),
      ],
      ['query'],
    ),
  'getToken' : IDL.Func([IDL.Text], [IDL.Opt(Token)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSampleData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sellToken' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateTokenPrice' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Token = IDL.Record({
    'fdv' : IDL.Float64,
    'change24h' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'liquidity' : IDL.Float64,
    'volume24h' : IDL.Float64,
    'holders' : IDL.Nat,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Trade = IDL.Record({
    'tradeType' : IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null }),
    'timestamp' : Time,
    'tokenPair' : IDL.Text,
    'price' : IDL.Float64,
    'amount' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOrUpdateToken' : IDL.Func([Token], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buyToken' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'getAllTokens' : IDL.Func([], [IDL.Vec(Token)], ['query']),
    'getAllTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getCallerHoldings' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Record({ 'amount' : IDL.Float64, 'symbol' : IDL.Text }),
              Token,
            )
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHoldings' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Record({ 'amount' : IDL.Float64, 'symbol' : IDL.Text }),
              Token,
            )
          ),
        ],
        ['query'],
      ),
    'getToken' : IDL.Func([IDL.Text], [IDL.Opt(Token)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSampleData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sellToken' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateTokenPrice' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };